# arrays with images and corresponding names
flagImg = ["afghanistan.PNG", "aland-islands.png", "albania.png", "algeria.png", "american-samoa.png",
"andorra.png", "angola.png", "anguilla.png", "antigua-and-barbuda.png", "argentina.png", "armenia.png",
"aruba.png", "australia.png", "azerbaijan.png", "bahrain.png", "balearic-islands.png", "bangladesh.png",
"barbados.png", "basque-country.png", "belarus.png", "belgium.png", "belize.png", "benin.png", "bermuda.png",
"bhutan.png", "bolivia.png", "bonaire.png", "bosnia-and-herzegovina.png", "botswana.png", "british-columbia.png",
"british-indian-ocean-territory.png", "british-virgin-islands.png", "brunei.png", "bulgaria.png",
"burkina-faso.png", "burundi.png", "cambodia.png", "cameroon.png", "canary-islands.png", "cape-verde.png",
"cayman-islands.png", "central-african-republic.png", "ceuta.png", "chad.png", "chile.png", "christmas-island.png",
"cocos-island.png", "colombia.png", "comoros.png", "cook-islands.png", "corsica.png", "costa-rica.png",
"croatia.png", "cuba.png", "cyprus.png", "czech-republic.png", "denmark.png", "dominica.png",
"dominican-republic.png", "ecuador.png", "egypt.png", "el-salvador.png", "england.png", "ethiopia.png",
"european-union.png", "faroe-islands.png", "fiji.png", "finland.png", "france.png", "french-polynesia.png",
"galapagos-islands.png", "gambia.png", "germany.png", "ghana.png", "greece.png", "guatemala.png", "guinea.png",
"hawaii.png", "honduras.png", "hong-kong.png", "hungary.png", "iceland.png", "indonesia.png", "iran.png",
"iraq.png", "ireland.png", "israel.png", "italy.png", "ivory-coast.png", "jamaica.png", "japan.png",
"jordan.png", "kazakhstan.png", "kenya.png", "kosovo.png", "laos.png", "latvia.png", "lebanon.png",
"lithuania.png", "luxembourg.png", "macao.png", "malaysia.png", "malta.png", "martinique.png",
"mauritius.png", "monaco.png", "morocco.png", "mozambique.png", "myanmar.png", "namibia.png",
"new-zealand.png", "nicaragua.png", "nigeria.png", "niue.png", "north-korea.png", "norway.png",
"oman.png", "orkney-islands.png", "pakistan.png", "palau.png", "panama.png", "peru.png", "philippines.png",
"poland.png", "puerto-rico.png", "qatar.png", "rapa-nui.png", "romania.png", "rwanda.png", "saba-island.png",
"saint-kitts-and-nevis.png", "saudi-arabia.png", "scotland.png", "serbia.png", "seychelles.png",
"sierra-leone.png", "singapore.png", "sint-eustatius.png", "sint-maarten.png", "slovakia.png", "slovenia.png",
"solomon-islands.png", "somaliland.png", "south-africa.png", "south-korea.png", "south-sudan.png", 
"spain.png", "st-lucia.png", "st-vincent-and-the-grenadines.png", "sweden.png", "switzerland.png",
"syria.png", "taiwan.png", "tanzania.png", "tokelau.png", "tonga.png", "transnistria.png", "tunisia.png",
"turkey.png", "turks-and-caicos.png", "uganda.png", "ukraine.png", "united-arab-emirates.png",
"united-kingdom.png", "united-nations.png", "united-states-of-america.png", "uruguay.png", "vanuatu.png",
"venezuela.png", "vietnam.png", "wales.png", "zambia.png" 
 ]

flagName = ["Afghanistan", "Aland Islands", "Albania", "Algieria", "American Samoa",
"Andorra", "Angola", "Anguilla", "Antigua and Barbuda", "Argentina", "Armenia",
"Aruba", "Australia", "Azerbaijan", "Bahrain", "Balearic Islands", "Bangladesh",
"Barbados", "Basque Country", "Belarus", "Belgium", "Belize", "Benin", "Bermuda",
"Bhutan", "Bolivia", "Bonaire", "Bosnia and Herzegovina", "Botswana", "British Columbia",
"British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria",
"Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canary Islands", "Cape Verde",
"Cayman Islands", "Central African Republic", "Ceuta", "Chad", "Chile", "Christmas Island",
"Cocos Island", "Colombia", "Comoros", "Cook Islands", "Corsica", "Costa Rica",
"Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Dominica",
"Dominican Republic", "Ecuador", "Egypt", "El Salvador", "England", "Ethiopia",
"European Union", "Faroe Islands", "Fiji", "Finland", "France", "French Polynesia",
"Galapagos Islands", "Gambia", "Germany", "Ghana", "Greece", "Guatemala", "Guinea",
"Hawaii", "Honduras", "Hong Kong", "Hungary", "Iceland", "Indonesia", "Iran",
"Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan",
"Jordan", "Kazakhstan", "Kenya", "Kosovo", "Laos", "Latvia", "Lebanon",
"Lithuania", "Luxembourg", "Macao", "Malaysia", "Malta", "Martinique",
"Mauritius", "Monaco", "Morocco", "Mozambique", "Myanmar", "Namibia",
"New Zealand", "Nicaragua", "Nigeria", "Niue", "North Korea", "Norway",
"Oman", "Orkney Islands", "Pakistan", "Palau", "Panama", "Peru", "Philippines",
"Poland", "Puerto Rico", "Qatar", "Rapa Nui", "Romania", "Rwanda", "Saba Island",
"Saint Kitts and Nevis", "Saudi Arabia", "Scotland", "Serbia", "Seychelles",
"Sierra Leone", "Singapore", "Sint Eustatius", "Sint Maarten", "Slovakia", "Slovenia",
"Solomon Islands", "Somaliland", "South Africa", "South Korea", "South Sudan", 
"Spain", "St Lucia", "St Vincent and the Grenadines", "Sweden", "Switzerland",
"Syria", "Taiwan", "Tanzania", "Tokelau", "Tonga", "Transnistria", "Tunisia",
"Turkey", "Turks and Caicos", "Uganda", "Ukraine", "United Arab Emirates",
"United Kingdom", "United Nations", "United States of America", "Uruguay", "Vanuatu",
"Venezuela", "Vietnam", "Wales", "Zambia"
 ]